config/routes.rb
Rails.application.routes.draw do

  get 'subjects/index' => 'subjects#index', as: :subjects_index

  get 'subjects/show/:id' => 'subjects#show', as: :subjects_show

  get 'subjects/new' => 'subjects#new', as: :subjects_new

  post 'subjects/create' => 'subjects#create', as: :subjects_create
  
  get 'subjects/edit/:id' => 'subjects#edit' , as: :subjects_edit

  patch 'subjects/update/:id' => 'subjects#update', as: :subjects_update

  delete 'subjects/destroy/:id' => 'subjects#destroy', as: :subjects_destroy
	
	post 'subjects/:id/comments/create' => 'comments#create', as: :comments_create
	

  get 'pages/index'

  get 'pages/show'

  devise_for :users
  
	root 'pages#index'
	

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :subject
	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :destroy
	
	validates :title, presence: true
	#validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  has_many :subjects
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def	create
		@subject = Subject.find(params[:id])
		@comment = Comment.new
  	@comment.detail = params[:comment][:detail]
  	@comment.user_id = current_user.id
  	@comment.subject_id = @subject.id
  	
  	if @comment.save
  		redirect_to subjects_show_path(@subject.id), notice: 'コメントを投稿しました'
  	else
  		
  	end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

	before_filter :authenticate_user!, only: [:new, :create]

  def index
  	@subjects = Subject.all
  end

  def show
  	@subject = Subject.find(params[:id])
  	@comments= Comment.where(subject_id: params[:id])
  	@comment = Comment.new
  end

  def new
  	@subject = Subject.new
  end

  def create
  	@subject = Subject.new
  	@subject.title = params[:subject][:title]
  	@subject.user_id = current_user.id
  	
  	if @subject.save
  		redirect_to subjects_index_path, notice: 'スレッドを作成しました'
  	else
  		redirect_to subjects_new_path, notice: 'スレッド作成エラー'
  	end
  end
	
	def edit
		@subject = Subject.find(params[:id])
	end
	
  def update
  	@subject = Subject.find(params[:id])
  	if @subject.update(:title => params[:subject][:title])
    	redirect_to subjects_index_path, notice: 'スレッドを編集しました'
    else
    	redirect_to subjects_edit_path, notice: 'スレッド編集エラー'
    end
  end

  def destroy
  	@subject = Subject.find(params[:id])
  	@subject.destroy
  	redirect_to subjects_index_path, notice: 'スレッドを削除しました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Forum3</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
        <nav>
        		掲示板 
        		&nbsp;&nbsp;
        		<%= link_to 'TOP', :root %>
        		&nbsp;&nbsp;
        		<%= link_to 'スレッド一覧', subjects_index_path %>
        		<%= link_to 'スレッド作成', subjects_new_path %>
        		&nbsp;&nbsp;
            <% if user_signed_in? %>
            <!--<strong><%= link_to current_user.username, pages_show_path %></strong>-->
            <%= link_to 'プロフィール変更', edit_user_registration_path %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to '新規登録', new_user_registration_path %>
            <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
        </nav>
        <br>
    </header>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

	<%= yield %>

	</body>
</html>

app/views/pages/index.html.erb
<h1>掲示板 TOP</h1>
<p>トップページです。</p>

app/views/pages/show.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>

app/views/subjects/destroy.html.erb
<h1>Subjects#destroy</h1>
<p>Find me in app/views/subjects/destroy.html.erb</p>

app/views/subjects/edit.html.erb
<h1>スレッド編集</h1>
<%= form_for @subject, :url => {:action => 'update'} do |f| %>
  <%= f.label :title, "スレッド名" %>
  <%= f.text_field :title %>
  <%= f.submit "更新" %>
<% end %>

app/views/subjects/index.html.erb
<h1>スレッド一覧</h1>

<table border=1>
	<tr><th>スレッド名</th><th>作成者</th><th>作成日時</th><th>編集</th><th>削除</th><tr>
	<% @subjects.each do |subject| %>
		<tr><td><%= link_to subject.title , subjects_show_path(subject.id) %></td>
		<td><%= subject.user.username%></td>
		<td><%= subject.created_at %></td>
		<td>
			<% if user_signed_in? %>
				<% if subject.user_id == current_user.id %>
					<%= link_to "編集" , subjects_edit_path(subject.id) %>
				<% end %>
			<% end %>
		</td>
		<td>
			<% if user_signed_in? %>
				<% if subject.user_id == current_user.id %>
					<%= link_to "削除" , subjects_destroy_path(subject.id), method: :delete, data: {confirm: "本当に削除しますか?"} %>
				<% end %>
			<% end %>
		</td><tr>				
	<% end %>
</table>
<br>
<%= link_to "TOPへ戻る", :root %>

app/views/subjects/new.html.erb
<h1>スレッド新規作成</h1>
<%= form_for @subject, :url => {:action => 'create'} do |f| %>
  <%= f.label :title, "スレッド名" %>
  <%= f.text_field :title %>
  <%= f.submit "作成" %>
<% end %>
<br>
<%= link_to "TOPへ戻る", :root %>

app/views/subjects/show.html.erb
<h2><%= @subject.title %></h2>

<% @comments.each_with_index do |comment, index| %>
	<p><%= "#{index.to_i + 1}" %> : <%= comment.user.username %> : <%= comment.created_at %></p>
	<p><%= simple_format(comment.detail) %></p>
	<br>
<% end %>

<br>
<h3>コメントの投稿</h3>
<% if user_signed_in? %>
	<%= form_for @comment, :url => {:controller => 'comments', :action => 'create'} do |f| %>
		<%= f.label :detail, "本文" %><br>
		<%= f.text_area :detail %><br>
		<%= f.submit "投稿" %>
	<% end %>
<% else %>
	<p>コメントするにはログインしてください。</p>
<% end %>

<br><br>
<%= link_to "スレッド一覧へ戻る", subjects_index_path %>

app/views/subjects/update.html.erb
<h1>Subjects#update</h1>
<p>Find me in app/views/subjects/update.html.erb</p>